// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top,hls_ip_2014_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.315000,HLS_SYN_LAT=4154765,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0}" *)

module top (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        INPUT_STREAM_TDATA,
        INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY,
        INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB,
        INPUT_STREAM_TUSER,
        INPUT_STREAM_TLAST,
        INPUT_STREAM_TID,
        INPUT_STREAM_TDEST,
        OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY,
        OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TUSER,
        OUTPUT_STREAM_TLAST,
        OUTPUT_STREAM_TID,
        OUTPUT_STREAM_TDEST
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 3'b000;
parameter    ap_ST_st2_fsm_1 = 3'b1;
parameter    ap_ST_st3_fsm_2 = 3'b10;
parameter    ap_ST_pp0_stg0_fsm_3 = 3'b11;
parameter    ap_ST_st6_fsm_4 = 3'b100;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv4_F = 4'b1111;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv11_438 = 11'b10000111000;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv11_780 = 11'b11110000000;
parameter    ap_const_lv11_77F = 11'b11101111111;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] INPUT_STREAM_TDATA;
input   INPUT_STREAM_TVALID;
output   INPUT_STREAM_TREADY;
input  [3:0] INPUT_STREAM_TKEEP;
input  [3:0] INPUT_STREAM_TSTRB;
input  [0:0] INPUT_STREAM_TUSER;
input  [0:0] INPUT_STREAM_TLAST;
input  [0:0] INPUT_STREAM_TID;
input  [0:0] INPUT_STREAM_TDEST;
output  [31:0] OUTPUT_STREAM_TDATA;
output   OUTPUT_STREAM_TVALID;
input   OUTPUT_STREAM_TREADY;
output  [3:0] OUTPUT_STREAM_TKEEP;
output  [3:0] OUTPUT_STREAM_TSTRB;
output  [0:0] OUTPUT_STREAM_TUSER;
output  [0:0] OUTPUT_STREAM_TLAST;
output  [0:0] OUTPUT_STREAM_TID;
output  [0:0] OUTPUT_STREAM_TDEST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg OUTPUT_STREAM_TVALID;
reg   [2:0] ap_CS_fsm = 3'b000;
reg   [10:0] p_3_i_reg_195;
wire   [10:0] i_V_fu_239_p2;
reg   [10:0] i_V_reg_313;
wire   [0:0] exitcond4_i_fu_245_p2;
reg   [0:0] exitcond4_i_reg_318;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
wire   [7:0] img_0_data_stream_0_V_dout;
wire    img_0_data_stream_0_V_empty_n;
reg    img_0_data_stream_0_V_read;
wire   [7:0] img_0_data_stream_1_V_dout;
wire    img_0_data_stream_1_V_empty_n;
reg    img_0_data_stream_1_V_read;
wire   [7:0] img_0_data_stream_2_V_dout;
wire    img_0_data_stream_2_V_empty_n;
reg    img_0_data_stream_2_V_read;
reg    ap_sig_bdd_72;
reg    ap_sig_ioackin_OUTPUT_STREAM_TREADY;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
wire   [10:0] j_V_fu_251_p2;
wire   [0:0] axi_last_V_fu_257_p2;
reg   [0:0] axi_last_V_reg_327;
wire   [0:0] exitcond3_i_fu_233_p2;
wire    grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_start;
wire    grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_done;
wire    grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_idle;
wire    grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_ready;
wire   [31:0] grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TDATA;
wire    grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TVALID;
wire    grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TREADY;
wire   [3:0] grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TKEEP;
wire   [3:0] grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TSTRB;
wire   [0:0] grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TUSER;
wire   [0:0] grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TLAST;
wire   [0:0] grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TID;
wire   [0:0] grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TDEST;
wire   [7:0] grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_0_V_din;
wire    grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_0_V_full_n;
wire    grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_0_V_write;
wire   [7:0] grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_1_V_din;
wire    grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_1_V_full_n;
wire    grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_1_V_write;
wire   [7:0] grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_2_V_din;
wire    grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_2_V_full_n;
wire    grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_2_V_write;
reg   [10:0] p_i_reg_184;
reg    grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_start_ap_start_reg = 1'b0;
wire   [7:0] img_0_data_stream_0_V_din;
wire    img_0_data_stream_0_V_full_n;
reg    img_0_data_stream_0_V_write;
wire   [7:0] img_0_data_stream_1_V_din;
wire    img_0_data_stream_1_V_full_n;
reg    img_0_data_stream_1_V_write;
wire   [7:0] img_0_data_stream_2_V_din;
wire    img_0_data_stream_2_V_full_n;
reg    img_0_data_stream_2_V_write;
reg   [0:0] tmp_user_V_fu_124;
reg    ap_reg_ioackin_OUTPUT_STREAM_TREADY = 1'b0;
reg   [2:0] ap_NS_fsm;
reg    top_ap_rst;
wire    img_0_data_stream_0_V_img_0_data_stream_0_V_fifo_U_ap_dummy_ce;
wire    img_0_data_stream_1_V_img_0_data_stream_1_V_fifo_U_ap_dummy_ce;
wire    img_0_data_stream_2_V_img_0_data_stream_2_V_fifo_U_ap_dummy_ce;


top_AXIvideo2Mat_32_1080_1920_32_s grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207(
    .ap_clk( ap_clk ),
    .ap_rst_n( ap_rst_n ),
    .ap_start( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_start ),
    .ap_done( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_done ),
    .ap_idle( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_idle ),
    .ap_ready( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_ready ),
    .INPUT_STREAM_TDATA( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TDATA ),
    .INPUT_STREAM_TVALID( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TVALID ),
    .INPUT_STREAM_TREADY( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TREADY ),
    .INPUT_STREAM_TKEEP( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TKEEP ),
    .INPUT_STREAM_TSTRB( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TSTRB ),
    .INPUT_STREAM_TUSER( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TUSER ),
    .INPUT_STREAM_TLAST( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TLAST ),
    .INPUT_STREAM_TID( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TID ),
    .INPUT_STREAM_TDEST( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TDEST ),
    .img_data_stream_0_V_din( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_0_V_din ),
    .img_data_stream_0_V_full_n( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_0_V_full_n ),
    .img_data_stream_0_V_write( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_0_V_write ),
    .img_data_stream_1_V_din( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_1_V_din ),
    .img_data_stream_1_V_full_n( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_1_V_full_n ),
    .img_data_stream_1_V_write( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_1_V_write ),
    .img_data_stream_2_V_din( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_2_V_din ),
    .img_data_stream_2_V_full_n( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_2_V_full_n ),
    .img_data_stream_2_V_write( grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_2_V_write )
);

FIFO_top_img_0_data_stream_0_V img_0_data_stream_0_V_img_0_data_stream_0_V_fifo_U(
    .clk( ap_clk ),
    .reset( top_ap_rst ),
    .if_read_ce( img_0_data_stream_0_V_img_0_data_stream_0_V_fifo_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_0_V_img_0_data_stream_0_V_fifo_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_0_V_din ),
    .if_full_n( img_0_data_stream_0_V_full_n ),
    .if_write( img_0_data_stream_0_V_write ),
    .if_dout( img_0_data_stream_0_V_dout ),
    .if_empty_n( img_0_data_stream_0_V_empty_n ),
    .if_read( img_0_data_stream_0_V_read )
);

FIFO_top_img_0_data_stream_1_V img_0_data_stream_1_V_img_0_data_stream_1_V_fifo_U(
    .clk( ap_clk ),
    .reset( top_ap_rst ),
    .if_read_ce( img_0_data_stream_1_V_img_0_data_stream_1_V_fifo_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_1_V_img_0_data_stream_1_V_fifo_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_1_V_din ),
    .if_full_n( img_0_data_stream_1_V_full_n ),
    .if_write( img_0_data_stream_1_V_write ),
    .if_dout( img_0_data_stream_1_V_dout ),
    .if_empty_n( img_0_data_stream_1_V_empty_n ),
    .if_read( img_0_data_stream_1_V_read )
);

FIFO_top_img_0_data_stream_2_V img_0_data_stream_2_V_img_0_data_stream_2_V_fifo_U(
    .clk( ap_clk ),
    .reset( top_ap_rst ),
    .if_read_ce( img_0_data_stream_2_V_img_0_data_stream_2_V_fifo_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_2_V_img_0_data_stream_2_V_fifo_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_2_V_din ),
    .if_full_n( img_0_data_stream_2_V_full_n ),
    .if_write( img_0_data_stream_2_V_write ),
    .if_dout( img_0_data_stream_2_V_dout ),
    .if_empty_n( img_0_data_stream_2_V_empty_n ),
    .if_read( img_0_data_stream_2_V_read )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst_n == 1'b0) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ioackin_OUTPUT_STREAM_TREADY assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ioackin_OUTPUT_STREAM_TREADY
    if (ap_rst_n == 1'b0) begin
        ap_reg_ioackin_OUTPUT_STREAM_TREADY <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_72 | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
            ap_reg_ioackin_OUTPUT_STREAM_TREADY <= ap_const_logic_0;
        end else if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_logic_1 == OUTPUT_STREAM_TREADY))) begin
            ap_reg_ioackin_OUTPUT_STREAM_TREADY <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst_n == 1'b0) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_72 | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(exitcond4_i_fu_245_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_i_fu_233_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst_n == 1'b0) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_72 | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (exitcond4_i_fu_245_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_i_fu_233_p2)) | ((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & ~((ap_sig_bdd_72 | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(exitcond4_i_fu_245_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_start_ap_start_reg
    if (ap_rst_n == 1'b0) begin
        grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
            grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_ready)) begin
            grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_72 | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (exitcond4_i_fu_245_p2 == ap_const_lv1_0))) begin
        p_3_i_reg_195 <= j_V_fu_251_p2;
    end else if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_i_fu_233_p2))) begin
        p_3_i_reg_195 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st6_fsm_4 == ap_CS_fsm)) begin
        p_i_reg_184 <= i_V_reg_313;
    end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_done))) begin
        p_i_reg_184 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_72 | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        tmp_user_V_fu_124 <= ap_const_lv1_0;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        tmp_user_V_fu_124 <= ap_const_lv1_1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_72 | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (exitcond4_i_fu_245_p2 == ap_const_lv1_0))) begin
        axi_last_V_reg_327 <= axi_last_V_fu_257_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_72 | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        exitcond4_i_reg_318 <= exitcond4_i_fu_245_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        i_V_reg_313 <= i_V_fu_239_p2;
    end
end

/// OUTPUT_STREAM_TVALID assign process. ///
always @ (ap_CS_fsm or exitcond4_i_reg_318 or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it1 or ap_reg_ioackin_OUTPUT_STREAM_TREADY)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (ap_const_logic_0 == ap_reg_ioackin_OUTPUT_STREAM_TREADY))) begin
        OUTPUT_STREAM_TVALID = ap_const_logic_1;
    end else begin
        OUTPUT_STREAM_TVALID = ap_const_logic_0;
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm or exitcond3_i_fu_233_p2)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond3_i_fu_233_p2))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond3_i_fu_233_p2)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond3_i_fu_233_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_ioackin_OUTPUT_STREAM_TREADY assign process. ///
always @ (OUTPUT_STREAM_TREADY or ap_reg_ioackin_OUTPUT_STREAM_TREADY)
begin
    if ((ap_const_logic_0 == ap_reg_ioackin_OUTPUT_STREAM_TREADY)) begin
        ap_sig_ioackin_OUTPUT_STREAM_TREADY = OUTPUT_STREAM_TREADY;
    end else begin
        ap_sig_ioackin_OUTPUT_STREAM_TREADY = ap_const_logic_1;
    end
end

/// img_0_data_stream_0_V_read assign process. ///
always @ (ap_CS_fsm or exitcond4_i_reg_318 or ap_sig_bdd_72 or ap_sig_ioackin_OUTPUT_STREAM_TREADY or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_72 | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        img_0_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        img_0_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// img_0_data_stream_0_V_write assign process. ///
always @ (ap_CS_fsm or grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_0_V_write)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) | (ap_ST_st2_fsm_1 == ap_CS_fsm))) begin
        img_0_data_stream_0_V_write = grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_0_V_write;
    end else begin
        img_0_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// img_0_data_stream_1_V_read assign process. ///
always @ (ap_CS_fsm or exitcond4_i_reg_318 or ap_sig_bdd_72 or ap_sig_ioackin_OUTPUT_STREAM_TREADY or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_72 | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        img_0_data_stream_1_V_read = ap_const_logic_1;
    end else begin
        img_0_data_stream_1_V_read = ap_const_logic_0;
    end
end

/// img_0_data_stream_1_V_write assign process. ///
always @ (ap_CS_fsm or grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_1_V_write)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) | (ap_ST_st2_fsm_1 == ap_CS_fsm))) begin
        img_0_data_stream_1_V_write = grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_1_V_write;
    end else begin
        img_0_data_stream_1_V_write = ap_const_logic_0;
    end
end

/// img_0_data_stream_2_V_read assign process. ///
always @ (ap_CS_fsm or exitcond4_i_reg_318 or ap_sig_bdd_72 or ap_sig_ioackin_OUTPUT_STREAM_TREADY or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_3 == ap_CS_fsm) & (exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_72 | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        img_0_data_stream_2_V_read = ap_const_logic_1;
    end else begin
        img_0_data_stream_2_V_read = ap_const_logic_0;
    end
end

/// img_0_data_stream_2_V_write assign process. ///
always @ (ap_CS_fsm or grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_2_V_write)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) | (ap_ST_st2_fsm_1 == ap_CS_fsm))) begin
        img_0_data_stream_2_V_write = grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_2_V_write;
    end else begin
        img_0_data_stream_2_V_write = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or exitcond4_i_fu_245_p2 or exitcond4_i_reg_318 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_72 or ap_sig_ioackin_OUTPUT_STREAM_TREADY or ap_reg_ppiten_pp0_it1 or exitcond3_i_fu_233_p2 or grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_done)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(ap_const_logic_0 == grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_done)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            if (~(ap_const_lv1_0 == exitcond3_i_fu_233_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end
        end
        ap_ST_pp0_stg0_fsm_3 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_72 | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(exitcond4_i_fu_245_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_72 | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (ap_const_logic_0 == ap_sig_ioackin_OUTPUT_STREAM_TREADY))) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(exitcond4_i_fu_245_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st6_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end
        end
        ap_ST_st6_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign INPUT_STREAM_TREADY = grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TREADY;
assign OUTPUT_STREAM_TDATA = {{{{{{ap_const_lv8_FF}, {img_0_data_stream_2_V_dout}}}, {img_0_data_stream_1_V_dout}}}, {img_0_data_stream_0_V_dout}};
assign OUTPUT_STREAM_TDEST = ap_const_lv1_0;
assign OUTPUT_STREAM_TID = ap_const_lv1_0;
assign OUTPUT_STREAM_TKEEP = ap_const_lv4_F;
assign OUTPUT_STREAM_TLAST = axi_last_V_reg_327;
assign OUTPUT_STREAM_TSTRB = ap_const_lv4_0;
assign OUTPUT_STREAM_TUSER = tmp_user_V_fu_124;

/// ap_sig_bdd_72 assign process. ///
always @ (exitcond4_i_reg_318 or img_0_data_stream_0_V_empty_n or img_0_data_stream_1_V_empty_n or img_0_data_stream_2_V_empty_n)
begin
    ap_sig_bdd_72 = (((img_0_data_stream_0_V_empty_n == ap_const_logic_0) & (exitcond4_i_reg_318 == ap_const_lv1_0)) | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (img_0_data_stream_1_V_empty_n == ap_const_logic_0)) | ((exitcond4_i_reg_318 == ap_const_lv1_0) & (img_0_data_stream_2_V_empty_n == ap_const_logic_0)));
end
assign axi_last_V_fu_257_p2 = (p_3_i_reg_195 == ap_const_lv11_77F? 1'b1: 1'b0);
assign exitcond3_i_fu_233_p2 = (p_i_reg_184 == ap_const_lv11_438? 1'b1: 1'b0);
assign exitcond4_i_fu_245_p2 = (p_3_i_reg_195 == ap_const_lv11_780? 1'b1: 1'b0);
assign grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TDATA = INPUT_STREAM_TDATA;
assign grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TDEST = INPUT_STREAM_TDEST;
assign grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TID = INPUT_STREAM_TID;
assign grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TKEEP = INPUT_STREAM_TKEEP;
assign grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TLAST = INPUT_STREAM_TLAST;
assign grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TSTRB = INPUT_STREAM_TSTRB;
assign grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TUSER = INPUT_STREAM_TUSER;
assign grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_INPUT_STREAM_TVALID = INPUT_STREAM_TVALID;
assign grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_start = grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_ap_start_ap_start_reg;
assign grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_0_V_full_n = img_0_data_stream_0_V_full_n;
assign grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_1_V_full_n = img_0_data_stream_1_V_full_n;
assign grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_2_V_full_n = img_0_data_stream_2_V_full_n;
assign i_V_fu_239_p2 = (p_i_reg_184 + ap_const_lv11_1);
assign img_0_data_stream_0_V_din = grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_0_V_din;
assign img_0_data_stream_0_V_img_0_data_stream_0_V_fifo_U_ap_dummy_ce = ap_const_logic_1;
assign img_0_data_stream_1_V_din = grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_1_V_din;
assign img_0_data_stream_1_V_img_0_data_stream_1_V_fifo_U_ap_dummy_ce = ap_const_logic_1;
assign img_0_data_stream_2_V_din = grp_top_AXIvideo2Mat_32_1080_1920_32_s_fu_207_img_data_stream_2_V_din;
assign img_0_data_stream_2_V_img_0_data_stream_2_V_fifo_U_ap_dummy_ce = ap_const_logic_1;
assign j_V_fu_251_p2 = (p_3_i_reg_195 + ap_const_lv11_1);

/// top_ap_rst assign process. ///
always @ (ap_rst_n)
begin
    top_ap_rst = ~ap_rst_n;
end


endmodule //top

