set_property PACKAGE_PIN W18 [get_ports HDMI_clk]
set_property PACKAGE_PIN Y13 [get_ports {HDMI_data[0]}]
set_property PACKAGE_PIN AA13 [get_ports {HDMI_data[1]}]
set_property PACKAGE_PIN W13 [get_ports {HDMI_data[10]}]
set_property PACKAGE_PIN W15 [get_ports {HDMI_data[11]}]
set_property PACKAGE_PIN V15 [get_ports {HDMI_data[12]}]
set_property PACKAGE_PIN U17 [get_ports {HDMI_data[13]}]
set_property PACKAGE_PIN V14 [get_ports {HDMI_data[14]}]
set_property PACKAGE_PIN V13 [get_ports {HDMI_data[15]}]
set_property PACKAGE_PIN AA14 [get_ports {HDMI_data[2]}]
set_property PACKAGE_PIN Y14 [get_ports {HDMI_data[3]}]
set_property PACKAGE_PIN AB15 [get_ports {HDMI_data[4]}]
set_property PACKAGE_PIN AB16 [get_ports {HDMI_data[5]}]
set_property PACKAGE_PIN AA16 [get_ports {HDMI_data[6]}]
set_property PACKAGE_PIN AB17 [get_ports {HDMI_data[7]}]
set_property PACKAGE_PIN AA17 [get_ports {HDMI_data[8]}]
set_property PACKAGE_PIN Y15 [get_ports {HDMI_data[9]}]
set_property PACKAGE_PIN U16 [get_ports HDMI_data_en]
set_property PACKAGE_PIN V17 [get_ports HDMI_hsync]
set_property PACKAGE_PIN W17 [get_ports HDMI_vsync]

set_property IOSTANDARD LVCMOS33 [get_ports HDMI_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_data_en]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_vsync]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list n_0_zynq_design_i]]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {zynq_design_i/bitcrop_0_M_AXI_TDATA[0]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[1]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[2]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[3]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[4]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[5]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[6]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[7]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[8]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[9]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[10]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[11]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[12]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[13]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[14]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[15]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[16]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[17]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[18]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[19]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[20]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[21]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[22]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[23]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[24]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[25]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[26]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[27]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[28]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[29]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[30]} {zynq_design_i/bitcrop_0_M_AXI_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property port_width 24 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {zynq_design_i/bitcrop_1_M_AXI_TDATA[0]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[1]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[2]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[3]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[4]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[5]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[6]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[7]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[8]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[9]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[10]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[11]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[12]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[13]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[14]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[15]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[16]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[17]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[18]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[19]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[20]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[21]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[22]} {zynq_design_i/bitcrop_1_M_AXI_TDATA[23]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[0]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[1]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[2]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[3]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[4]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[5]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[6]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[7]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[8]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[9]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[10]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[11]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[12]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[13]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[14]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[15]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[16]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[17]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[18]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[19]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[20]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[21]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[22]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[23]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[24]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[25]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[26]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[27]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[28]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[29]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[30]} {zynq_design_i/top_0_OUTPUT_STREAM_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property port_width 24 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {zynq_design_i/v_tpg_0_video_out_TDATA[0]} {zynq_design_i/v_tpg_0_video_out_TDATA[1]} {zynq_design_i/v_tpg_0_video_out_TDATA[2]} {zynq_design_i/v_tpg_0_video_out_TDATA[3]} {zynq_design_i/v_tpg_0_video_out_TDATA[4]} {zynq_design_i/v_tpg_0_video_out_TDATA[5]} {zynq_design_i/v_tpg_0_video_out_TDATA[6]} {zynq_design_i/v_tpg_0_video_out_TDATA[7]} {zynq_design_i/v_tpg_0_video_out_TDATA[8]} {zynq_design_i/v_tpg_0_video_out_TDATA[9]} {zynq_design_i/v_tpg_0_video_out_TDATA[10]} {zynq_design_i/v_tpg_0_video_out_TDATA[11]} {zynq_design_i/v_tpg_0_video_out_TDATA[12]} {zynq_design_i/v_tpg_0_video_out_TDATA[13]} {zynq_design_i/v_tpg_0_video_out_TDATA[14]} {zynq_design_i/v_tpg_0_video_out_TDATA[15]} {zynq_design_i/v_tpg_0_video_out_TDATA[16]} {zynq_design_i/v_tpg_0_video_out_TDATA[17]} {zynq_design_i/v_tpg_0_video_out_TDATA[18]} {zynq_design_i/v_tpg_0_video_out_TDATA[19]} {zynq_design_i/v_tpg_0_video_out_TDATA[20]} {zynq_design_i/v_tpg_0_video_out_TDATA[21]} {zynq_design_i/v_tpg_0_video_out_TDATA[22]} {zynq_design_i/v_tpg_0_video_out_TDATA[23]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list zynq_design_i/bitcrop_0_M_AXI_TLAST]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list zynq_design_i/bitcrop_0_M_AXI_TREADY]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list zynq_design_i/bitcrop_0_M_AXI_TUSER]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list zynq_design_i/bitcrop_0_M_AXI_TVALID]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list zynq_design_i/bitcrop_1_M_AXI_TLAST]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list zynq_design_i/bitcrop_1_M_AXI_TREADY]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list zynq_design_i/bitcrop_1_M_AXI_TUSER]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list zynq_design_i/bitcrop_1_M_AXI_TVALID]]
connect_debug_port u_ila_0/probe12 [get_nets [list zynq_design_i/top_0_OUTPUT_STREAM_TLAST]]
connect_debug_port u_ila_0/probe13 [get_nets [list zynq_design_i/top_0_OUTPUT_STREAM_TREADY]]
connect_debug_port u_ila_0/probe14 [get_nets [list zynq_design_i/top_0_OUTPUT_STREAM_TUSER]]
connect_debug_port u_ila_0/probe15 [get_nets [list zynq_design_i/top_0_OUTPUT_STREAM_TVALID]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list zynq_design_i/v_tpg_0_video_out_TLAST]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list zynq_design_i/v_tpg_0_video_out_TREADY]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list zynq_design_i/v_tpg_0_video_out_TUSER]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list zynq_design_i/v_tpg_0_video_out_TVALID]]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets n_0_zynq_design_i]
