# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons.xdc

# Block Designs: bd/zynq_design/zynq_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design || ORIG_REF_NAME==zynq_design}]

# IP: bd/zynq_design/ip/zynq_design_processing_system7_0_0/zynq_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_processing_system7_0_0 || ORIG_REF_NAME==zynq_design_processing_system7_0_0}]

# IP: bd/zynq_design/ip/zynq_design_v_tpg_0_0/zynq_design_v_tpg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_v_tpg_0_0 || ORIG_REF_NAME==zynq_design_v_tpg_0_0}]

# IP: bd/zynq_design/ip/zynq_design_bitcrop_0_0/zynq_design_bitcrop_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_bitcrop_0_0 || ORIG_REF_NAME==zynq_design_bitcrop_0_0}]

# IP: bd/zynq_design/ip/zynq_design_bitcrop_1_0/zynq_design_bitcrop_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_bitcrop_1_0 || ORIG_REF_NAME==zynq_design_bitcrop_1_0}]

# IP: bd/zynq_design/ip/zynq_design_v_rgb2ycrcb_0_0/zynq_design_v_rgb2ycrcb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==zynq_design_v_rgb2ycrcb_0_0}]

# IP: bd/zynq_design/ip/zynq_design_v_yuv444to422_0_0/zynq_design_v_yuv444to422_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_v_yuv444to422_0_0 || ORIG_REF_NAME==zynq_design_v_yuv444to422_0_0}]

# IP: bd/zynq_design/ip/zynq_design_v_axi4s_vid_out_0_0/zynq_design_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==zynq_design_v_axi4s_vid_out_0_0}]

# IP: bd/zynq_design/ip/zynq_design_v_tc_0_0/zynq_design_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_v_tc_0_0 || ORIG_REF_NAME==zynq_design_v_tc_0_0}]

# IP: bd/zynq_design/ip/zynq_design_xlconstant_0_0/zynq_design_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_xlconstant_0_0 || ORIG_REF_NAME==zynq_design_xlconstant_0_0}]

# XDC: bd/zynq_design/ip/zynq_design_processing_system7_0_0/zynq_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_processing_system7_0_0 || ORIG_REF_NAME==zynq_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/zynq_design/ip/zynq_design_v_tpg_0_0/zynq_design_v_tpg_0_0_ooc.xdc

# XDC: bd/zynq_design/ip/zynq_design_v_tpg_0_0/zynq_design_v_tpg_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_v_tpg_0_0 || ORIG_REF_NAME==zynq_design_v_tpg_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_design/ip/zynq_design_v_rgb2ycrcb_0_0/zynq_design_v_rgb2ycrcb_0_0_ooc.xdc

# XDC: bd/zynq_design/ip/zynq_design_v_rgb2ycrcb_0_0/zynq_design_v_rgb2ycrcb_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==zynq_design_v_rgb2ycrcb_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_design/ip/zynq_design_v_axi4s_vid_out_0_0/zynq_design_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/zynq_design/ip/zynq_design_v_axi4s_vid_out_0_0/zynq_design_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==zynq_design_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/zynq_design/ip/zynq_design_v_tc_0_0/zynq_design_v_tc_0_0_ooc.xdc

# XDC: bd/zynq_design/ip/zynq_design_v_tc_0_0/zynq_design_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_design_v_tc_0_0 || ORIG_REF_NAME==zynq_design_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_design/zynq_design_ooc.xdc
