# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
set_msg_config  -id {Chipscope 16-111}  -suppress 
create_project -in_memory -part xc7z020clg484-1
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:0.9 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths C:/Users/onlybecool/Thesis/git_videopasstrough/vivado_ip_repo [current_fileset]

add_files C:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/sources_1/bd/zynq_design/zynq_design.bd
set_property used_in_implementation false [get_files -all c:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/sources_1/bd/zynq_design/ip/zynq_design_processing_system7_0_0/zynq_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/sources_1/bd/zynq_design/ip/zynq_design_v_tpg_0_0/zynq_design_v_tpg_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/sources_1/bd/zynq_design/ip/zynq_design_v_tpg_0_0/zynq_design_v_tpg_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/sources_1/bd/zynq_design/ip/zynq_design_v_rgb2ycrcb_0_0/zynq_design_v_rgb2ycrcb_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/sources_1/bd/zynq_design/ip/zynq_design_v_rgb2ycrcb_0_0/zynq_design_v_rgb2ycrcb_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/sources_1/bd/zynq_design/ip/zynq_design_v_axi4s_vid_out_0_0/zynq_design_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/sources_1/bd/zynq_design/ip/zynq_design_v_axi4s_vid_out_0_0/zynq_design_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/sources_1/bd/zynq_design/ip/zynq_design_v_tc_0_0/zynq_design_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/sources_1/bd/zynq_design/ip/zynq_design_v_tc_0_0/zynq_design_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all C:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/sources_1/bd/zynq_design/zynq_design_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/sources_1/bd/zynq_design/zynq_design.bd]

read_vhdl -library xil_defaultlib C:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/sources_1/bd/zynq_design/hdl/zynq_design_wrapper.vhd
read_xdc C:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files C:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.srcs/constrs_1/new/cons.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01/git_videopasstrough_v_1_01.cache/wt [current_project]
set_property parent.project_dir C:/Users/onlybecool/Thesis/git_videopasstrough/git_videopasstrough_v_1_01 [current_project]
catch { write_hwdef -file zynq_design_wrapper.hwdef }
synth_design -top zynq_design_wrapper -part xc7z020clg484-1 -flatten_hierarchy none
write_checkpoint zynq_design_wrapper.dcp
report_utilization -file zynq_design_wrapper_utilization_synth.rpt -pb zynq_design_wrapper_utilization_synth.pb
